apiVersion: v1
kind: Service
metadata:
  name: door2-sync-service
  labels:
    name: door2-sync-service
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: door2-sync
  type: ClusterIP
