apiVersion: apps/v1
kind: Deployment
metadata:
  name: door2-sync-deployment
  namespace: ca-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: door2-sync
  template:
    metadata:
      labels:
        app: door2-sync
    spec:
      containers:
        - name: door2-sync
          image: noellowry/door:v1
