apiVersion: apps/v1
kind: Deployment
metadata:
  name: seccon-sync-deployment
  namespace: ca-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seccon-sync
  template:
    metadata:
      labels:
        app: seccon-sync
    spec:
      containers:
        - name: seccon-sync
          image: noellowry/seccon:v1
          args: ["redis-service:6379", "2000", "50", "door1", "door2"]
          ports:
          - containerPort: 8080	  
        - name: redis
          image: redis
          ports:
          - containerPort: 6379
