apiVersion: v1
kind: Service
metadata:
  name: seccon-sync-service
  namespace: ca-dev
  labels:
    app: seccon-sync-service
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 8080
    nodePort: 30916
  selector:
    app: seccon-sync
  type: NodePort
